# Generated by Django 3.0.6 on 2020-05-08 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimalType', models.CharField(max_length=15, unique=True, verbose_name='Вид животного')),
                ('AnimalType_slug', models.SlugField(max_length=15, verbose_name='Вид животного для URL')),
                ('AnimalPhoto', models.ImageField(blank=True, upload_to='animals_photos', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
            },
        ),
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breed', models.CharField(max_length=64, unique=True, verbose_name='Порода')),
                ('Breed_slug', models.SlugField(blank=True, default=None, max_length=64, null=True, verbose_name='Порода животного для URL')),
                ('AnimalPhoto', models.ImageField(blank=True, upload_to='breed_photos', verbose_name='Фото породы')),
                ('Animal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='animal_breed', to='ourpets.Animal', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Порода животного',
                'verbose_name_plural': 'Породы животных',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=100, verbose_name='Кличка')),
                ('Age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Возраст')),
                ('Description', models.TextField(default=None, verbose_name='Описание')),
                ('date_registration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Данные регистрации')),
                ('PetPhoto', models.ImageField(blank=True, upload_to='pets_photos', verbose_name='Фото питомца')),
                ('HoldPlace', models.BooleanField(choices=[(True, 'В приюте'), (False, 'Вне приюта')], default=True, verbose_name='Местонахождение')),
                ('Breed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pet_breed', to='ourpets.AnimalBreed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
