# Generated by Django 3.0.6 on 2020-05-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourpets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='AnimalPhoto',
            new_name='animalphoto',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='AnimalType',
            new_name='animaltype',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='AnimalType_slug',
            new_name='animaltype_slug',
        ),
        migrations.RenameField(
            model_name='animalbreed',
            old_name='Animal',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='animalbreed',
            old_name='AnimalPhoto',
            new_name='animalphoto',
        ),
        migrations.RenameField(
            model_name='animalbreed',
            old_name='Breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='animalbreed',
            old_name='Breed_slug',
            new_name='breed_slug',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='HoldPlace',
            new_name='holdplace',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='PetPhoto',
            new_name='petphoto',
        ),
    ]
