# Generated by Django 3.0.6 on 2020-05-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourpets', '0002_auto_20200508_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalbreed',
            old_name='animalphoto',
            new_name='breedphoto',
        ),
    ]
