# Generated by Django 3.0.6 on 2020-05-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourpets', '0003_auto_20200508_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pol',
            field=models.CharField(choices=[('m', 'Мальчик'), ('f', 'Девочка')], default='m', max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
